In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
print(os.getcwd())

c:\Users\user\Desktop\Kifiya\AlphaCare-Insurance-Solutions-Analysis\notebooks

In [4]:

import sys
sys.path.append(r'c:\Users\user\Desktop\Kifiya\AlphaCare-Insurance-Solutions-Analysis\scripts')

# Import experience_analytics modules
from testingh import (
    load_data
)

In [5]:
import importlib
import testingh

importlib.reload(testingh)

# Loading and Handling the dataset

In [1]:
# Step 1: Data Cleaning and Preparation

import pandas as pd

# Load the data
data = pd.read_csv(r'C:\Users\Eyor.G\Desktop\KIFIYA Projects\AlphaCare-Insurance-Solutions-Analysis\data\MachineLearningRating_v3.txt', delimiter='|')

# Display the first few rows of the data
data.head()

# Check for null values
null_values = data.isnull().sum()
print("Null Values:\n", null_values)

# Handling missing values
# Drop columns with more than 50% missing values
threshold = len(data) * 0.5
data = data.dropna(thresh=threshold, axis=1)

# Impute missing values for categorical data with mode
for column in data.select_dtypes(include=['object']).columns:
    data[column].fillna(data[column].mode()[0], inplace=True)

# Impute missing values for numerical data with mean
for column in data.select_dtypes(include=['number']).columns:
    data[column].fillna(data[column].mean(), inplace=True)

# Verify there are no more missing values
null_values_after = data.isnull().sum()
print("Null Values after Handling:\n", null_values_after)

# Summary of the data
data.info()
data.describe()

C:\Users\Eyor.G\AppData\Local\Temp\ipykernel_14084\2284012418.py:6: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\Eyor.G\Desktop\KIFIYA Projects\AlphaCare-Insurance-Solutions-Analysis\data\MachineLearningRating_v3.txt', delimiter='|')

Null Values:
 UnderwrittenCoverID               0
PolicyID                          0
TransactionMonth                  0
IsVATRegistered                   0
Citizenship                       0
LegalType                         0
Title                             0
Language                          0
Bank                         145961
AccountType                   40232
MaritalStatus                  8259
Gender                         9536
Country                           0
Province                          0
PostalCode                        0
MainCrestaZone                    0
SubCrestaZone                     0
ItemType                          0
mmcode                          552
VehicleType                     552
RegistrationYear                  0
make                            552
Model                           552
Cylinders                       552
cubiccapacity                   552
kilowatts                       552
bodytype                        552
NumberOfDoors                   552
VehicleIntroDate                552
CustomValueEstimate          779642
AlarmImmobiliser                  0
TrackingDevice                    0
CapitalOutstanding                2
NewVehicle                   153295
WrittenOff                   641901
Rebuilt                      641901
Converted                    641901
CrossBorder                  999400
NumberOfVehiclesInFleet     1000098
SumInsured                        0
TermFrequency                     0
CalculatedPremiumPerTerm          0
ExcessSelected                    0
CoverCategory                     0
CoverType                         0
CoverGroup                        0
Section                           0
Product                           0
StatutoryClass                    0
StatutoryRiskType                 0
TotalPremium                      0
TotalClaims                       0
dtype: int64

C:\Users\Eyor.G\AppData\Local\Temp\ipykernel_14084\2284012418.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].mode()[0], inplace=True)
C:\Users\Eyor.G\AppData\Local\Temp\ipykernel_14084\2284012418.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].mean(), inplace=True)

Null Values after Handling:
 UnderwrittenCoverID         0
PolicyID                    0
TransactionMonth            0
IsVATRegistered             0
Citizenship                 0
LegalType                   0
Title                       0
Language                    0
Bank                        0
AccountType                 0
MaritalStatus               0
Gender                      0
Country                     0
Province                    0
PostalCode                  0
MainCrestaZone              0
SubCrestaZone               0
ItemType                    0
mmcode                      0
VehicleType                 0
RegistrationYear            0
make                        0
Model                       0
Cylinders                   0
cubiccapacity               0
kilowatts                   0
bodytype                    0
NumberOfDoors               0
VehicleIntroDate            0
AlarmImmobiliser            0
TrackingDevice              0
CapitalOutstanding          0
NewVehicle                  0
SumInsured                  0
TermFrequency               0
CalculatedPremiumPerTerm    0
ExcessSelected              0
CoverCategory               0
CoverType                   0
CoverGroup                  0
Section                     0
Product                     0
StatutoryClass              0
StatutoryRiskType           0
TotalPremium                0
TotalClaims                 0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000098 entries, 0 to 1000097
Data columns (total 46 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   UnderwrittenCoverID       1000098 non-null  int64
 1   PolicyID                  1000098 non-null  int64
 2   TransactionMonth          1000098 non-null  object
 3   IsVATRegistered           1000098 non-null  bool
 4   Citizenship               1000098 non-null  object
 5   LegalType                 1000098 non-null  object
 6   Title                     1000098 non-null  object
 7   Language                  1000098 non-null  object
 8   Bank                      1000098 non-null  object
 9   AccountType               1000098 non-null  object
 10  MaritalStatus             1000098 non-null  object
 11  Gender                    1000098 non-null  object
 12  Country                   1000098 non-null  object
 13  Province                  1000098 non-null  object
 14  PostalCode                1000098 non-null  int64
 15  MainCrestaZone            1000098 non-null  object
 16  SubCrestaZone             1000098 non-null  object
 17  ItemType                  1000098 non-null  object
 18  mmcode                    1000098 non-null  float64
 19  VehicleType               1000098 non-null  object
 20  RegistrationYear          1000098 non-null  int64
 21  make                      1000098 non-null  object
 22  Model                     1000098 non-null  object
 23  Cylinders                 1000098 non-null  float64
 24  cubiccapacity             1000098 non-null  float64
 25  kilowatts                 1000098 non-null  float64
 26  bodytype                  1000098 non-null  object
 27  NumberOfDoors             1000098 non-null  float64
 28  VehicleIntroDate          1000098 non-null  object
 29  AlarmImmobiliser          1000098 non-null  object
 30  TrackingDevice            1000098 non-null  object
 31  CapitalOutstanding        1000098 non-null  object
 32  NewVehicle                1000098 non-null  object
 33  SumInsured                1000098 non-null  float64
 34  TermFrequency             1000098 non-null  object
 35  CalculatedPremiumPerTerm  1000098 non-null  float64
 36  ExcessSelected            1000098 non-null  object
 37  CoverCategory             1000098 non-null  object
 38  CoverType                 1000098 non-null  object
 39  CoverGroup                1000098 non-null  object
 40  Section                   1000098 non-null  object
 41  Product                   1000098 non-null  object
 42  StatutoryClass            1000098 non-null  object
 43  StatutoryRiskType         1000098 non-null  object
 44  TotalPremium              1000098 non-null  float64
 45  TotalClaims               1000098 non-null  float64
dtypes: bool(1), float64(9), int64(4), object(32)
memory usage: 344.3+ MB

,UnderwrittenCoverID,PolicyID,PostalCode,mmcode,RegistrationYear,Cylinders,cubiccapacity,kilowatts,NumberOfDoors,SumInsured,CalculatedPremiumPerTerm,TotalPremium,TotalClaims
count,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06,1.000098e+06
mean,1.048175e+05,7.956682e+03,3.020601e+03,5.487770e+07,2.010225e+03,4.046642e+00,2.466743e+03,9.720792e+01,4.019250e+00,6.041727e+05,1.178757e+02,6.190550e+01,6.486119e+01
std,6.329371e+04,5.290039e+03,2.649854e+03,1.360005e+07,3.261391e+00,2.939390e-01,4.426784e+02,1.938790e+01,4.681852e-01,1.508332e+06,3.997017e+02,2.302845e+02,2.384075e+03
min,1.000000e+00,1.400000e+01,1.000000e+00,4.041200e+06,1.987000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-02,0.000000e+00,-7.825768e+02,-1.200241e+04
25%,5.514300e+04,4.500000e+03,8.270000e+02,6.005692e+07,2.008000e+03,4.000000e+00,2.237000e+03,7.500000e+01,4.000000e+00,5.000000e+03,3.224800e+00,0.000000e+00,0.000000e+00
50%,9.408300e+04,7.071000e+03,2.000000e+03,6.005842e+07,2.011000e+03,4.000000e+00,2.694000e+03,1.110000e+02,4.000000e+00,7.500000e+03,8.436900e+00,2.178333e+00,0.000000e+00
75%,1.391900e+05,1.107700e+04,4.180000e+03,6.005842e+07,2.013000e+03,4.000000e+00,2.694000e+03,1.110000e+02,4.000000e+00,2.500000e+05,9.000000e+01,2.192982e+01,0.000000e+00
max,3.011750e+05,2.324600e+04,9.870000e+03,6.506535e+07,2.015000e+03,1.000000e+01,1.288000e+04,3.090000e+02,6.000000e+00,1.263620e+07,7.442217e+04,6.528260e+04,3.930921e+05

# Segmentation and Hypothesis Testing

In [7]:
# Import the custom module for A/B Hypothesis Testing
import testingh as abt

# Get unique values for segmentation
unique_provinces = data['Province'].unique()
unique_postalcodes = data['PostalCode'].unique()

print("Unique Provinces:\n", unique_provinces)
print("Unique Postal Codes:\n", unique_postalcodes)

Unique Provinces:
 ['Gauteng' 'KwaZulu-Natal' 'Mpumalanga' 'Eastern Cape' 'Western Cape'
 'Limpopo' 'North West' 'Free State' 'Northern Cape']
Unique Postal Codes:
 [1459 1513 1619 1625 1629 1852 1982 2007 2066 4093 2000 1577 1610 2410
 6200  122 1520 1709 1739 4000 4066 4091 4342 4359 7784  970 6213 6390
 1868 4310  299  309  152  181 1821 4449 4037  139 4074 1057 7100 9725
 1863 1875 2001 2091 3170 3950 1021 2380  300  302  458 7750  157 4811
 4930 5000 5090 5160 5219 5410 5920 6025 6139 5040 6201 6212 6231 9744
    1    8   64   84  162  164 8000  182  183  186  190 5326  192  194
  199  200  201  208  258  264 1431 1441 1455 1494 1496  284 9762 1507
 1540 1559 1571 1724 1754 1757 1759 1779 1803 1804 1806 1809 1818 1828
 1830 1862 1864 1865 1984 2014 2019 2021 2040 2090 2188 2198 3180 3200
 3245 3310 3380 3609 3610 3612 3613 3370 3600 3629 3630 3650 3780 3900
 3934 3973 5143 3880 3882 3915 4001 4004 4011 4023 4027 4051 4052 4053
 4056 4057 4059 4060 4061 4063 4071 4089 4092 4105 4110 4111 4126 4137
 4140 4180 4200 4240 4260 4309 4340 4360 4450 4700  530  555  556  607
  699  738  827 1022 1123 1133 2375 2415 2499 4068 2951 2952 3602 4182
 4490 1030  250  308  316  335  404  407  314  322  472 2744 8345 8566
 8601 8701 6705 6708 6835 3887 8599 7130 7140 7160 7441 7455 7490 7500
 7570 7405 7571 7580 7620 7655  450 7764 7780 7785 7786 7793 3910 7806
 7888 7941 7945 1980  902 4820 5100 5120 5201 5247 6140 6500 9323 9730
 9869    4   22  118  120  147  161 7460  177 7646  179  184  198 1458
 1491 1541 1550 1612 1666 1682 1751 1841 1860 1884 1939  331  303  338
 8580 8584 2620 8570 7925 2061 7947 2094 2128 2194 3290 3635 4100 4275
 4339 4454  628  700  742  812  942 1020 1059 1060 1061 1085 4058  310
  318  400  456  470  479 2531 2865 2876 8160 8190 6838 6875 7195 7437
 7501 7503 7600 8020 8051 5252 5319 5321 5670 6059 6211 6242 9300 9301
 9325 5600 9431 9447 9745 9750 9781    2    5   29  125  153  168  172
  269 1426 1449 1454 1462 1475 1575 1632 1640 1740 1811 1813 1835 1874
 1928 1940 1947 1949 2069 2070 2092 2190 2192 2195 2940 3201 3217 3607
 3680 3700 3750 3802 3815 3855 7350 4069 4070 4084 4099 4133 4145 4380
 4470  557  561  608  609  623  690  727  739  745  746  821  951 1024
 1035 1047 1050 1053 1062 1098 1365  311  320  333  360  362  370  382
  449  457  459  473  474 2502 2574 2610 2740 2840 2841 2860 2868 2869
 2890 8149 8301 8309 8530 6600 6848 7101 7220 7525 7550 7690 7783 7800
 8001 2920 4810 5070 5099 5130 5180 5480 5601 5611 5900 6229  116  277
 1424 1548 1620  305 1745 1805 1812 1900 1948 1983 2010 2093 2125 2170
 3000 3306 3616 3652 3965 3350 4019 4148 4400 4457 4491 4730  600  982
 1026 1027 1034 1055 1120 1280 1342 1360 2735 2745 2881 7103 7439 7493
 7782 7788 7975 8060 4960 5050 5140 5320 5322 5380 5608 6105 9459 9700
 9870   17   31   37   49   81  112  121  149  154  268 1401 1405 1423
 1425 1460 1471 1560 1570 1618 1685 1700 1710 1781 1820 1930 1932 1747
 2056 2191 2196 2197 2930 3257 3615 3925 3969 4008 4030 4065 4094 4132
 4150 4220 2055 4399 4680  708  748  920 1039 1064 1068 1072 1150 1389
  301 4125  355  365  379  465  467  476 2870 8165 8446 6506 7000 7133
 7406 7581 7700 7751 8017 4800 5170 5500 5700 6000 6001 6205 9445 9600
   35   66 1457 1501 1693 1774 1819 1824 1827 1837 2017 3105 3276 3297
 3381 3920 4144 4170  617  925  950  993 1054 1124 1126 1245 2420  380
  414  422  475 2500 2534 2754 2791 8170 6571 7310 7380 7442 7530 7612
 7745 7755 8040 5185 3135 4401  939 6280    6   21  151 1466 1519 1725
 1791 2143 3624 4031 4062 4075 4270 4302 4319  631  743  790 1003 1023
 1372 2351  337  455 2880 2882 7200 7569 7801 8005 5365 5614 1630 1851
 1867 2008 3010 3203 3670 4691  737 1250  477 7144 4990 5200 5209 5660
 5720 9334 9752 9868   54  129  187  195  220 1687 1742 1834 1963 2189
 3080 3150 3250 3837 3838 3865 3935 3968 4250  751  931 1000 1038 1129
 2230  292 1807  317  399  431  469  485  486 2835 8271 8447 6570 7340
 7532 7626 4980 4430 7456 5470 6241 9306 9830   44 6720  193  196 1474
 1861 2018 2063 2095 3651 4405 6810 1058  453  495 2571 2619 8306 8575
 6625 7802  356  984 5253 5362 5435 5455 9499 9756  101  143  175 1448
 1743 1801 1869 2028 3242 3270  721  736  802  945 1240 2231  307  351
  388 2507 1829 1914 6350  837 6120 1421 1154  325 7540 2470 6850 4480
 8586 1631 1688 3107 3300 1052 7395 7463 7789 4184 2570 8577 1794 1833
 8240 1185 6840 5687  807    7 2057 1127 7579  132 3742 3660 1692 9720
 2157 4171 8460 2210 2031 2146 7560 4067 2037 1522 3655 2193 7798 2062
 3740 3830 4016  371 7763  286  402 6070   46 4025  462  466 2766 7450
  430 1744 4087 3974 4455 7582 7280 7790 7583  510 6836 4005 2530  621
 7760 1748 1665 7766  340 6655]

In [13]:
# Define actual values for segmentation based on the unique values 
provinces_a = ['Gauteng', 'KwaZulu-Natal', 'Mpumalanga', 'Eastern Cape', 'Western Cape']
provinces_b = ['Limpopo', 'North West', 'Free State', 'Northern Cape']
zipcodes_a = [1459, 1513, 1619, 1625, 1629]
zipcodes_b = [1852, 1982, 2007, 2066, 4093]

In [14]:
# Define actual values for segmentation based on the unique values 
provinces_a = ['Gauteng', 'KwaZulu-Natal', 'Mpumalanga', 'Eastern Cape', 'Western Cape']
provinces_b = ['Limpopo', 'North West', 'Free State', 'Northern Cape']
zipcodes_a = [1459, 1513, 1619, 1625, 1629]
zipcodes_b = [1852, 1982, 2007, 2066, 4093]

# Evaluate each hypothesis separately with detailed logging

# Hypothesis 1: There are no risk differences across provinces
data['Province_Group'] = data['Province'].apply(lambda x: 'Group_A' if x in provinces_a else ('Group_B' if x in provinces_b else 'Other'))
group_a_provinces = data[data['Province_Group'] == 'Group_A']
group_b_provinces = data[data['Province_Group'] == 'Group_B']
print(f"Size of Group A (Provinces): {len(group_a_provinces)}, Size of Group B (Provinces): {len(group_b_provinces)}")

p_value_provinces = abt.evaluate_hypothesis(data, 'Province_Group', ['Group_A'], ['Group_B'], 'TotalClaims', 't-test')
print(f"Province hypothesis p-value: {p_value_provinces}")

Size of Group A (Provinces): 817496, Size of Group B (Provinces): 182602
Evaluating hypothesis for feature: Province_Group, Group 1 values: ['Group_A'], Group 2 values: ['Group_B']
Group A sample size: 817496
Group B sample size: 182602
Province hypothesis p-value: 1.2656563578109116e-06

In [15]:
# Hypothesis 2: There are no risk differences between zip codes
data['ZipCode_Group'] = data['PostalCode'].apply(lambda x: 'Group_A' if x in zipcodes_a else ('Group_B' if x in zipcodes_b else 'Other'))
group_a_zipcodes = data[data['ZipCode_Group'] == 'Group_A']
group_b_zipcodes = data[data['ZipCode_Group'] == 'Group_B']
print(f"Size of Group A (ZipCodes): {len(group_a_zipcodes)}, Size of Group B (ZipCodes): {len(group_b_zipcodes)}")

p_value_zipcodes = abt.evaluate_hypothesis(data, 'ZipCode_Group', ['Group_A'], ['Group_B'], 'TotalClaims', 't-test')
print(f"ZipCode hypothesis p-value: {p_value_zipcodes}")

Size of Group A (ZipCodes): 3103, Size of Group B (ZipCodes): 4637
Evaluating hypothesis for feature: ZipCode_Group, Group 1 values: ['Group_A'], Group 2 values: ['Group_B']
Group A sample size: 3103
Group B sample size: 4637
ZipCode hypothesis p-value: 0.2768618153541921

In [16]:
# Hypothesis 3: There are no significant margin (profit) differences between zip codes
data['Margin'] = data['TotalPremium'] - data['TotalClaims']
p_value_margin = abt.evaluate_hypothesis(data, 'ZipCode_Group', ['Group_A'], ['Group_B'], 'Margin', 't-test')
print(f"Margin hypothesis p-value: {p_value_margin}")

Evaluating hypothesis for feature: ZipCode_Group, Group 1 values: ['Group_A'], Group 2 values: ['Group_B']
Group A sample size: 3103
Group B sample size: 4637
Margin hypothesis p-value: 0.23014643973302473

In [19]:
# Hypothesis 4: There are no significant risk differences between Women and Men
group_a_gender = data[data['Gender'] == 'Female']
group_b_gender = data[data['Gender'] == 'Male']
print(f"Size of Group A (Women): {len(group_a_gender)}, Size of Group B (Men): {len(group_b_gender)}")

p_value_gender = abt.evaluate_hypothesis(data, 'Gender', ['Female'], ['Male'], 'TotalClaims', 't-test')
print(f"Gender hypothesis p-value: {p_value_gender}")

Size of Group A (Women): 6755, Size of Group B (Men): 42817
Evaluating hypothesis for feature: Gender, Group 1 values: ['Female'], Group 2 values: ['Male']
Group A sample size: 6755
Group B sample size: 42817
Gender hypothesis p-value: 0.8041073961270343

In [21]:
# Compile and analyze results
results = {
    'Provinces': p_value_provinces,
    'ZipCodes': p_value_zipcodes,
    'Margin': p_value_margin,
    'Gender': p_value_gender
}

# Analyze results
abt.analyze_results(results)

Reject the null hypothesis for Provinces.
Fail to reject the null hypothesis for ZipCodes.
Fail to reject the null hypothesis for Margin.
Fail to reject the null hypothesis for Gender.